//====================================
//DQFULP
// Audio Data
//====================================

#ifndef DQFULP_AUDIODATA_DEF
#define DQFULP_AUDIODATA_DEF

#define NIL_SFX			-1
#define MAX_SAMPLES		10
#define MAX_VOLUME		100
#define MIN_VOLUME		0
#define LOOP			true
#define NOLOOP			false

enum eAudioType
{
	AudioUndefined,
	AudioSFX,
	AudioTrack,
	AudioAmb,
	AudioVO
};

enum eAudio
{
	Audio_Nil = -1,

	//Menu sounds effects
	aSFXLogoSplash,
	aSFXClick,
	aSFXCrystal,
	aSFXMouseover,

	//Game sound effects	
	aSFXMagic,

	aSFXFootsteps0,
	aSFXFootsteps1,
	aSFXFootsteps2,
	aSFXRefill, 	
	aSFXRefill2, 	

	aSFXRefill3, 	
	aSFXDanger0,
	aSFXGlassBtn,	
	aSFXFolly,
	aSFXMagic1,

	aSFXMagic2,
	aSFXMagic3,
	aSFXMagic4,
	aSFXPain, 

	aSFXInvBoxOpen,	
	aSFXNotifyHard,
	aSFXNotifySoft,
	aSFXNotifySoft2,
	aSFXWoodShake,

	aSFXInvBoxDrop,
	aSFXLoader,

	aSFXpopup,
	aSFXpopdown,

	aSFXSoundExperience,

	//MENU_SFX
	aSFXKidGiggle,
	aSFXMnuBTNClick,
	aSFXMnuMouseOver,
	aSFXMnuChapterClick,
	aSFXMnuModeClick,
	aSFXMnuModeLocked,
	aSFXMnuProfNameClick,
	aSFXMnuProfNameType,
	aSFXMnuProfNameDelete,
	aSFXMnuSliderClick,
	aSFXMnuSliderMove,
	aSFXMnuTickClick,
	aSFXMnuChapterSlide,

	aSFXKidRoomBell1,
	aSFXKidRoomBell2,
	aSFXKidRoomBell3,
	aSFXKidRoomBell4,

	//HUD_SFX
	aSFXDiaClose,
	aSFXDiaJournalAdd,
	aSFXDiaObjAdd,
	aSFXDiaOpen,
	aSFXDiaPageTurn,
	aSFXDiaTabClick,
	aSFXHintDischarge,
	aSFXHintFullCharge,
	aSFXInvArrowClick,
	aSFXInvCollectv1,
	aSFXInvCollectv2,
	aSFXInvCollectv3,
	aSFXInvItemPick,
	aSFXInvWrongDrop,
	aSFXMapClick,
	aSFXMapMouseOver,
	aSFXTeleShow,

	//Match3
	aSFXMatch3Win1,
	aSFXMatch3Win2,
	aSFXMatch3Win3,
	aSFXMatch3Win4,
	aSFXMatch3Click,
	aSFXMatch3WrongClick,
	aSFXmatch3Good,
	aSFXmatch3Better,
	aSFXmatch3Best,
	aSFXmatch3Reward,

	//L1_SFX
	aSFXL1ThunderV1,
	aSFXL1ThunderV2,
	aSFXJrnlFlyer,
	//S1_SFX
	aSFXL1S1BagLockPartFixed,
	aSFXL1S1BagLockPartPicked,
	aSFXL1S1BagLockPartPlaced,
	aSFXL1S1BagLockPopupSFX,
	aSFXL1S1BagLatchOpen,
	aSFXL1S1BagOpen2,
	aSFXL1S1BagZipSFX,
	aSFXL1S1LeafRemove,
	aSFXL1S1BranchCutSFX,
	aSFXL1S1KidsPaintingClicked,
	aSFXL1S1KidsPaintingComplete,
	aSFXL1S1KidsPaintingRightClick,
	aSFXL1S1KidsPaintingWrongClick,
	aSFXL1S1RajaTakingJames,
	//S2_SFX
	aSFXL1S2FuseRotate,
	aSFXL1S3P1Click,
	aSFXL1S3P1FuseFix,
	aSFXL1S3P1LeverTurn,
	aSFXL1S3P1PowerOff,
	aSFXL1S3P1PowerOn,
	aSFXL1S3P1Rotate,
	aSFXL1S3P1Spark1,
	aSFXL1S3P1Spark2,
	aSFXL1S3P1Spark3,
	aSFXL1S3P1Spark4,
	aSFXL1S3P1GreenLit,

	aSFXL1S2LovePopup,
	aSFXL1S2MonkeyClicked,
	aSFXL1S2MonkeyTakeBanana,
	aSFXL1S2P1SackRemoved,
	aSFXL1S2P1CrowBarUse,
	aSFXL1S2WolfHowl,
	aSFXL1S2RopeCut,
	aSFXL1S2StickFixed,

	//S3_SFX
	aSFXL1S3HOBlueBtnClick,
	aSFXL1S3HOBlueBtnSwap,
	aSFXL1S3HOCoverOpen,
	aSFXL1S3HOEmblemClicked,
	aSFXL1S3HOEmblemFixed,
	aSFXL1S3HOGemClicked,
	aSFXL1S3HOGemDoorSlideOpen,
	aSFXL1S3HOGemDoorSlideOpen2,
	aSFXL1S3HOGemWrongClick,
	aSFXL1S3HOKeyDrag,
	aSFXL1S3HOKeyFixed,
	aSFXL1S3HOObjectSilClicked,
	aSFXL1S3HOSlideTwoSidesOpen,
	aSFXL1S3HOWin,

	aSFXL1S3CatAttack,
	aSFXL1S3ObjectMoveed,
	aSFXL1S3RajaTakeJames,
	aSFXL1S3ShelfNotePicked,
	aSFXL1S3SelfOpen,
	aSFXL1S3ShelfLockOpen,
	aSFXL1S3ShelfFindDiff,
	aSFXL1S3StickUsed,
	//S4_SFX
	aSFXL1S4CreekPortalLoop,
	aSFXL1S4CreekPortalPop,
	aSFXL1S4SecretDoorOpen,

	aSFXL1S4PaintingSlide,
	aSFXL1S4PaintingLocksOpen,
	aSFXL1S4PaintingPuzzleSolved,

	aSFXL1S4PortraitTear,
	aSFXL1S4PotraitTurned,
	
	aSFXL1S4P1NagaKeyFixed,
	aSFXL1S4P1DrawerOpened,
	aSFXL1S4P1DiaryTake,
	aSFXL1S4P1KeyLost,
	aSFXL1S4P1WaxMelted,
	aSFXL1S4BeetleFixedOnBook,
	aSFXL1S4BeetleJoin,
	aSFXL1S4BookOpened,
	aSFXL1S4BookPicked,
	aSFXL1S4BooksMoved,
	aSFXL1S4BoxOpen,
	aSFXL1S4KeySetPick,
	aSFXL1S4CodeSymbolFixed,
	aSFXL1S4CoinPicked,
	aSFXL1S4CoinUsed,
	aSFXL1S4ChairSway,

	aSFXL1S4DiaryCurrencySlide,
	aSFXL1S4DiaryStampSlide,
	aSFXL1S4DiaryNotePicked,
	aSFXL1S4DiaryPageTurn,
	aSFXL1S4DiaryPicked,

	aSFXL1S4ShadowFlipDisc,
	aSFXL1S4ShadowKetSetPlaced,
	aSFXL1S4ShadowKeySelected,
	aSFXL1S4ShadowLockReveled,
	aSFXL1S4ShadowPieceFixed,
	aSFXL1S4ShadowPieceMatched,
	aSFXL1S4ShadowPieceSelect,
	aSFXL1S4ShadowPieceSlide,
	aSFXL1S4ShadowRightKey,
	aSFXL1S4ShadowWrongKey,
	//S5_SFX
	aSFXL1S5DynamiteAcidPour,
	aSFXL1S5DynamiteBottleCapPlaced,
	aSFXL1S5DynamiteCrystalCrush,
	aSFXL1S5DynamiteCrystalInBottle,
	aSFXL1S5DynamiteCrystalsCollected,
	aSFXL1S5DynamiteAcidCapOpen,
	aSFXL1S5DynamitePowder,
	aSFXL1S5DynamiteBoxOpen,

	aSFXL1S5BookOpenPzlSolved,
	aSFXL1S5ClockHandleFix,
	aSFXL1S5ClothMove,
	aSFXL1S5CoinFixInbox,
	aSFXL1S5DrawerOpen,

	aSFXL1S5EagleMouthOpen,
	aSFXL1S5GarudaEmblemFix,
	aSFXL1S5MonkeyHandOpen,
	aSFXL1S5PestleFixinMortar,
	aSFXL1S5PopDown,

	aSFXL1S5Popup,
	aSFXL1S5RingboxOpen,
	aSFXL1S5RotateMBEmblems,
	aSFXL1S5SwapMB1,
	aSFXL1S5SwapMB2,


	aSFXL1S5BombPlaced,
	aSFXL1S5BombExplode,
	aSFXL1S5ExplodeCough,

	aSFXL1S5HammerJoin,
	aSFXL1S5HammerUsed,

	aSFXL1S5LampLite,
	aSFXL1S5PlankMoved,
	
	//S6_SFX
	aSFXL1S6BoxDroped,
	aSFXL1S6BroomPicked,
	aSFXL1S6CanPlaced,
	aSFXL1S6DieselFill,
	aSFXL1S6DogWhine,
	aSFXL1S6DogBarkV1,
	aSFXL1S6DogBarkV2,
	aSFXL1S6PumpFixed,
	aSFXL1S6HoseFixed,
	aSFXL1S6PumpingDiesel,
	aSFXL1S6SwitchOn,
	aSFXL1S6WebCleaned,
	//S6HO_SFX
	aSFXL1S6HOBeetleClicked,
	aSFXL1S6HOBeetlePicked,
	aSFXL1S6HOBladeUsed,
	aSFXL1S6HOClipClicked,
	aSFXL1S6HOClothRub,
	aSFXL1S6HOFunnelPartJoin,
	aSFXL1S6HOGloveUsed,
	aSFXL1S6HOOilDipperUsed,
	aSFXL1S6HOOpenBox,
	aSFXL1S6HOOpenLockWithClip,
	aSFXL1S6HOSlideObject,
	aSFXL1S6HOSquirrelClicked,
	aSFXL1S6HOSquirrelEat,
	aSFXL1S6HOTapeUsed,
	
	//S7_SFX
	aSFXL1S7BoatEngineStart,
	aSFXL1S7BoatKeyFixed,
	aSFXL1S7DieselCapClose,
	aSFXL1S7DieselCapOpen,
	aSFXL1S7DieselFunnelPlaced,
	aSFXL1S7DieselFunnelRemoved,
	aSFXL1S7DieselPoured,
	aSFXL1S7RopeCut,
	aSFXL1S7PlankFixed,

	//LEVEL 2

	//S1_SFX
	aSFXL2S2HOObjectClickv1,
	aSFXL2S2HOObjectClickv2,
	aSFXL2S2HOObjectClickv3,
	aSFXL2S2HOPartsCombineAnim,

	//S3_SFX
	//S4_SFX
	//S5_SFX
	//S6_SFX
	aSFXL2S6HOHalfCompleted,

	//VOICEOVER
	aVOMenuTest,
	aVOL1S1_1Raja,
	aVOL1S1_2Raja,
	aVOL1S1_3Raja,
	aVOL1S1_4Raja,
	aVOL1S3Talk1_1Raja,
	aVOL1S3Talk1_2Mary,
	aVOL1S3Talk1_3Mary,
	aVOL1S3Talk1_4Mary,
	aVOL1S3Talk1_5Raja,
	aVOL1S3Talk1_6Mary,
	aVOL1S3Talk2_1Raja,
	aVOL1S3Talk2_2Raja,
	aVOL1S3Talk2_3Mary,
	aVOL1S3Talk2_4Raja,
	aVOL1S3Talk2_5Mary,
	aVOL1S3Talk2_6Raja,
	aVOL1S3Talk2_7Raja,
	aVOL1S3Talk0_Raja,
	aVOL1S3Talk3_Raja,
	aVOL1S4Talk1_1Creek,
	aVOL1S4Talk1_2Creek,
	aVOL1S4Talk1_3Creek,
	aVOL1S4Talk1_4Creek,

	aVOL1MaryRefS1_1,
	aVOL1MaryRefS2_1,
	aVOL1MaryRefS2_2,
	aVOL1MaryRefS3_1,
	aVOL1MaryRefS3_2,
	aVOL1MaryRefS4_1,
	aVOL1MaryRefS5_1,
	aVOL1MaryRefS5_2,
	aVOL1MaryRefS5_3,
	aVOL1MaryRefS6_1,
	aVOL1MaryRefS7_1,

	aVOL2S5Talk1_1Moopan,
	aVOL2S5Talk1_2Mary,
	aVOL2S5Talk1_3Moopan,
	aVOL2S5Talk1_4Mary,
	aVOL2S5Talk2_1Moopan,
	aVOL2S5Talk2_2Moopan,
	aVOL2S5Talk2_3Moopan,
	aVOL2S5Talk2_4Moopan,
	aVOL2S5Talk2_5Moopan,
	aVOL2S5Talk2_6Mary,

	aVOL2MaryRefS2_1,
	aVOL2MaryRefS4_1,
	aVOL2MaryRefS5_1,
	aVOL2MaryRefS6_1,

	aVOL3MaryRefS2_1,
	aVOL3MaryRefS3_1,
	aVOL3MaryRefS4_1,
	aVOL3MaryRefS5_1,

	aVOL3S5Talk1_1Ann,
	aVOL3S5Talk1_2Ann,
	aVOL3S5Talk1_3Mary,
	aVOL3S5Talk1_4Ann,

	aVOL4MaryRefS4_1,
	aVOL4MaryRefS4_2,
	aVOL4MaryRefS4_3,
	aVOL4MaryRefS5_1,

	aVOL5MaryRefS1_1,
	aVOL5MaryRefS3_1,
	aVOL5MaryRefS4_1,
	aVOL5MaryRefS6_1,
	aVOL5S5Talk1_1Latika,
	aVOL5S5Talk1_2Latika,
	aVOL5S5Talk1_3Latika,
	aVOL5S5Talk1_4Latika,
	aVOL5S5Talk1_5Latika,
	aVOL5S5Talk2_1Latika,
	aVOL5S5Talk2_2Latika,
	aVOL5S5Talk2_3Latika,
	aVOL5S5Talk3_1Tree,
	aVOL5S5Talk3_2Tree,
	aVOL5S5Talk3_3Mary,
	aVOL5S5Talk3_3Tree,
	aVOL5S5Talk4_1Tree,
	aVOL5S5Talk4_2Tree,
	aVOL5TreeRefS6_1,

	aVOL6DescS1_1,
	aVOL6DescS1_2,
	aVOL6DescS1_3,
	aVOL6DescS1_4,
	aVOL6DescS1_5,
	aVOL6MaryRefS1_1,
	aVOL6MaryRefS1_2,
	aVOL6MaryRefS1_3,
	aVOL6MaryRefS3_1,
	aVOL6MaryRefS4_1,
	aVOL6MaryRefS5_1,
	aVOL6MaryRefS5_2,
	aVOL6MaryRefS5_3,
	aVOL6MaryRefS6_1,
	aVOL6MaryRefS6_2,
	aVOL6NoteVOS4_1,
	aVOL6NoteVOS4_2,
	aVOL6NoteVOS4_3,
	aVOL6S3Talk1_1Mary,
	aVOL6S3Talk1_2Mary,
	aVOL6S3Talk1_3James,
	aVOL6S3Talk1_4James,
	aVOL6S3Talk1_5James,
	aVOL6S4Talk1_1Rockman,
	aVOL6S4Talk1_2Rockman,
	aVOL6S4Talk1_3Mary,
	aVOL6S4Talk1_4Rockman,
	aVOL6S5Talk1_1Mary,
	aVOL6S5Talk1_2Sofia,
	aVOL6S5Talk1_3Sofia,
	aVOL6S5Talk1_4Mary,
	aVOL6S5Talk2_1Sofia,

	aVOL7MaryRefS2_1,
	aVOL7MaryRefS3_1,
	aVOL7MaryRefS3_2,
	aVOL7MaryRefS3_3,
	aVOL7MaryRefS3_4,
	aVOL7MaryRefS5_1,
	aVOL7NoteVOS3_1,
	aVOL7S3Talk1_1Anatha,
	aVOL7S3Talk1_2Anatha,
	aVOL7S4Talk1_1Mary,
	aVOL7S4Talk1_2Ameha,
	aVOL7S4Talk1_3Ameha,
	aVOL7S4Talk1_4Ameha,
	aVOL7S4Talk1_5Ameha,
	aVOL7S4Talk1_6Mary,

	aVOL8GuruRefS1_1,
	aVOL8GuruRefS2_1,

	//Ambiances
	aAmbRain,
	aAmbBeachLoop,

	aAmbS1Beach,
	aAmbS2FrontyardUnlit,
	aAmbS2FrontyardLit,
	aAmbS2PuzFuse,
	aAmbS3FoyerUnlit,
	aAmbS3FoyerLit,
	aAmbS3HODoorMetal,
	aAmbS3PuzShelf,
	aAmbS4Bedroom,
	aAmbS4PuzPainting,
	aAmbS4PuzShadowhand,
	aAmbS5TreasureRoom,
	aAmbS5PuzDynamite,
	aAmbS5TunnelDoor,
	aAmbS6ShedRoom,
	aAmbS7Boatdock,

	aAmbEndOfDemo,

	aAmbs1ForestEntrance,
	aAmbs1Undeground,
	aAmbs2MangoPuzzle,
	aAmbs2NagaCave,
	aAmbs2NagaHead,
	aAmbs3CaveMouth,
	aAmbs4Cave,
	aAmbs5MedicinePuzzle,
	aAmbs5MoopansDen,
	aAmbs6TunnelEnd,
	aAmbs6WaterHo,
	aAmbs7ArmorPuzzle,

	aAmbL3s2Maze,
	aAmbL3s3BlockPuzzle,
	aAmbL3s3Pool,
	aAmbL3s3UnderwaterPuzzle,
	aAmbL3s4Fountain,
	aAmbL3s4FountainHO,
	aAmbL3s5Cliff,
	aAmbL3s1FortEntrance,
	aAmbL3s1LadderHO,
	aAmbL3s1LionHead,
	aAmbL3s2FortInterior,

	aAmbL4s5SwapPuzzleAmb,
	aAmbL4s1MushroomPuzzleAmb,
	aAmbL4s1ShoeHOAmb,
	aAmbL4s1SwapEntranceAmb,
	aAmbL4s2AlligatorPuzzleAmb,
	aAmbL4s2FanPuzzleAmb,
	aAmbL4s2RiverSideAmb,
	aAmbL4s3CaveAmb,
	aAmbL4s3DoorPuzzleAmb,
	aAmbL4s3FireMakingPuzzleAmb,
	aAmbL4s4BinocularHOAmb,
	aAmbL4s4HillTopAmb,
	aAmbL4s5HillSideAmb,

	aAmbL5s3UnderwaterHOAmb,
	aAmbL5s4DungeonAmb,
	aAmbL5s4HandCuffPuzzleAmb,
	aAmbL5s5MoutainBelowAmb,
	aAmbL5s5SunclockPuzzleAmd,
	aAmbL5s6MountainTopAmb,
	aAmbL5s6TreeHOAmb,
	aAmbL5s1BlockPuzzleAmb,
	aAmbL5s1TigerDistantAmb,
	aAmbL5s2TigerCloseUpAmb,
	aAmbL5s3DungeonDoorPuzzleAmb,
	aAmbL5s3PondAmb,

	aAmbL6s4FloatingIsland4Amb,
	aAmbL6s4PortalAmb,
	aAmbL6s4ProtalMiniGameAmb,
	aAmbL6s5MarysDreamAmb,
	aAmbL6s5TabletMiniGameAmb,
	aAmbL6s1DescriptionHOAmb,
	aAmbL6s1FloatingIsland1Amb,
	aAmbL6s2FloatingIsland2Amb,
	aAmbL6s2PineGumPuzzleAmb,
	aAmbL6s2SphereHOamb,
	aAmbL6s3FloatingIsland3Amb,
	aAmbL6s3PathwayPuzzleAmb,

	aAmbL7s5SopiaAmb,
	aAmbL7puzzleAmb,
	aAmbL7s1VolcanoAmb,
	aAmbL7s2LasyaPrisonAmb,
	aAmbL7s3HavenAmb,
	aAmbL7s4AmeehaAmb,
	
	aAmbL8s3BanyanTreeAmb,
	aAmbL8s3TreeHOAmb,
	aAmbL8s4PoolAmb,
	aAmbL8s5VolcanoLandAmb,
	aAmbL8puzzleAmb,
	aAmbL8s1ShukrasPalaceAmb,
	aAmbL8s2GardenAmb,
	
	//Level_tracks
	aTrackL1Broken,
	aTrackL1Mansion,
	aTrackL1Trapped,
	aTrackL1EscapePlan,
	aTrackL1Hunted,
	aTrackL1Puzzle,
	aTrackL1KidsPuzzleBGM,
	aTrackLevel2,
	aTrackLevel3,
	aTrackLevel4,
	aTrackLevel5,
	aTrackMenu,
	aTrackBonusCredit,

	aTrackL2theme,
	aTrackL2theme1,
	aTrackL2ho,
	aTrackL2puzzle,
	aTrackL2s7Puzzle,

	aTrackL3theme,
	aTrackL3ho,
	aTrackL3puzzle,

	aTrackL4theme,
	aTrackL4ho,
	aTrackL4puzzle,

	aTrackL5theme,
	aTrackL5ho,
	aTrackL5puzzle,

	aTrackL6theme,
	aTrackL6ho,
	aTrackL6puzzle,
	aTrackL6s3Puzzle,

	aTrackL7theme,
	aTrackL7ho,
	aTrackL7puzzle,
	aTrackL7s5Theme,

	aTrackL8theme,
	aTrackL8ho,
	aTrackL8puzzle,
	

	//cutscenes MUSIC tracks
	aTrackCutscnGameIntro,
	aTrackCutscnS1KidsPainting,
	aTrackCutscnS4CreekAppears,
	aTrackCutscnS4MayaPush,
	aTrackCutscnS5MayaAttack,
	aTrackCutscnS5TunnelEscape,
	aTrackCutscnS6Newspaper,
	aTrackCutscnS7BoatOutro,
	aTrackEndCutscene,

	

	//Music tracks
	aTrackCredits,
	aTrackKidRoom,

	Audio_Max
};
	extern const char* AudioFiles[Audio_Max];
#endif